// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zukicxckcsmtciqgkhrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1a2ljeGNrY3NtdGNpcWdraHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTgyMjUsImV4cCI6MjA1Nzk3NDIyNX0.cnRY1wslujO0USUVkclt9Iel3Ceiq7zTRwKaLvBoizY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);